sudo: false
language: csharp
solution: FileHelpers.sln
install:
  - nuget restore FileHelpers.sln
#  - nuget restore FileHelpers.Analyzer/FileHelpers.Analyzer.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug FileHelpers.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./FileHelpers.Tests/Release/FileHelpers.Tests.dll -exclude=NotOnMono
#  - xbuild /p:Configuration=Debug FileHelpers.Analyzer/FileHelpers.Analyzer.sln
#  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./FileHelpers.Analyzer/FileHelpers.Analyzer/FileHelpers.Analyzer.Test/Debug/FileHelpers.Analyzer.Test.dll